num1 = int (input("Digite o seu primeiro número:" ))
num2 = int (input("Digite o seu segundo número:" ))
num3 = int (input("Digite o seu terceiro número:" ))
num4 = int (input("Digite o seu quarto número:" ))
num5 = int (input("Digite o seu quinto número:" ))
num6 = int (input("Digite o seu sexto número:" ))
num7 = int (input("Digite o seu sétimo número:" ))
num8 = int (input("Digite o seu oitavo número:" ))
num9 = int (input("Digite o seu nono número:" ))
num10 = int (input("Digite o seu décimo número:" ))
print ("O resultado somando todos os número digitados é :", num1+num2+num3+num4+num5+num6+num7+num8+num9+num10)